server:
  port: ${SERVER_PORT:8080}


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:postgresql://localhost:5432/tourism'
    username: 'postgres'
    password: 'dobby0303'
