server:
  port: ${SERVER_PORT:8080}


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:database}'
    username: '${DB_USER:login}'
    password: '${DB_PASS:password}'
